Netlogix:
  Sentry:
    scope:
      environment:
        # See Configuration/Environment.yaml for settings
        # Only one environment provider should be active!
        'Netlogix\Sentry\Scope\Environment\FlowSettings': true

      extra: []

      release:
        # See Configuration/Settings.Release.yaml for settings
        # Only one release provider should be active!
        'Netlogix\Sentry\Scope\Release\PathPattern': true

      tags:
        'Netlogix\Sentry\Scope\Tags\FlowEnvironment': true

      user:
        'Netlogix\Sentry\Scope\User\FlowAccount': true
