Netlogix:
  Sentry:

    release:
      # Used by Netlogix\Sentry\Scope\Release\FlowSettings
      setting: '%env:SENTRY_RELEASE%'

      # Used by Netlogix\Sentry\Scope\Release\PathPattern
      # Path to use for extraction of release
      pathToMatch: '%FLOW_PATH_ROOT%'

      # Pattern to extract current release from file path
      # This pattern is matched against pathToMatch
      pathPattern: '~/releases/(\d{14})$~'
