name: unittests

on: [ push, pull_request ]

jobs:
  unittests:
    name: '[PHP ${{ matrix.php-versions }} | Flow ${{ matrix.flow-versions }}] Unit Tests'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ 7.2, 7.3, 7.4 ]
        flow-versions: [ 6.3, 7.0 ]
        exclude:
          # Disable Flow 7.0 on PHP 7.2, as 7.3 is required
          - php-versions: 7.2
            flow-versions: 7.0

    env:
      APP_ENV: true
      FLOW_CONTEXT: Testing/Unit
      FLOW_DIST_FOLDER: flow-base-distribution

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, json, zlib, iconv, intl, pdo_sqlite
          ini-values: opcache.fast_shutdown=0

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-versions }}-flow-${{ matrix.flow-versions }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php-${{ matrix.php-versions }}-flow-${{ matrix.flow-versions }}-composer-
            php-${{ matrix.php-versions }}-flow-
      - name: Install composer dependencies
        run: composer create-project neos/flow-base-distribution ${{ env.FLOW_DIST_FOLDER }} --prefer-dist --no-progress "^${{ matrix.flow-versions }}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.FLOW_DIST_FOLDER }}/DistributionPackages/Netlogix.Sentry

      - name: Install netlogix/sentry
        run: composer require netlogix/sentry:@dev
        working-directory: ${{ env.FLOW_DIST_FOLDER }}

      - name: Run tests
        run: bin/phpunit -c DistributionPackages/Netlogix.Sentry/phpunit.xml.dist --testsuite="Unit" --bootstrap "Build/BuildEssentials/PhpUnit/UnitTestBootstrap.php"
        working-directory: ${{ env.FLOW_DIST_FOLDER }}
